In [4]:
from lib import FredClient

In [5]:
fred = FredClient()

fred.get("gdp").tail(100)

                value
date
2001-04-01  10599.000
2001-07-01  10598.020
2001-10-01  10660.465
2002-01-01  10783.500
2002-04-01  10887.460
...               ...
2025-01-01  30042.113
2025-04-01  30485.729
2025-07-01  31098.027
2025-10-01  31422.526
2026-01-01  31819.464

[100 rows x 1 columns]

In [6]:
fred.get_series(
    series_id="GDP",
    start="2020-01-01",
    end="2024-12-31",
    frequency="q",
    aggregation_method="avg",
)

                value
date
2020-01-01  21751.238
2020-04-01  19958.291
2020-07-01  21704.437
2020-10-01  22087.160
2021-01-01  22680.693
2021-04-01  23425.910
2021-07-01  23982.379
2021-10-01  24813.600
2022-01-01  25250.347
2022-04-01  25861.292
2022-07-01  26336.304
2022-10-01  26770.514
2023-01-01  27216.445
2023-04-01  27530.055
2023-07-01  28074.846
2023-10-01  28424.722
2024-01-01  28708.161
2024-04-01  29147.044
2024-07-01  29511.664
2024-10-01  29825.182